apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-mgmt
  labels:
    app: device
spec:
  replicas: 1
  selector:
    matchLabels:
      app: device
  template:
    metadata:
      labels:
        app: device
    spec:
      containers:
      - name: device-mgmt
        image: device-mgmt:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8181
          name: http
          protocol: TCP
